### ISSUE TITLE
"const char" to LPCWSTR Error

### ISSUE THREAD

**Issue by dawningtruth** [AnyarInc/gnugraph#1]
On Visual Studio 2017, the following errors are created:

Severity Code: E0167	
Description:  argument of type "const char *" is incompatible with parameter of type "LPCWSTR"	LearnGNU_Graph
File: c:\..\gnugraphpiping.h	
Line: 158	

AND

Severity Code: C2664	
Description: 'BOOL CreateProcessW(LPCWSTR,LPWSTR,LPSECURITY_ATTRIBUTES,LPSECURITY_ATTRIBUTES,BOOL,DWORD,LPVOID,LPCWSTR,LPSTARTUPINFOW,LPPROCESS_INFORMATION)': cannot convert argument 1 from 'const char *' to 'LPCWSTR'
File: c:\..\gnugraphpiping.h
Line:	167	

Screenshot for convenience:

https://snag.gy/jU956B.jpg

**Comment by stephenberry** [comment]
@dawningtruth 
Pardon the long delay, but the issue has to do with the character set in Visual Studios.
If you go into the solution's project properties, go under the General tab to the section titled "Project Defaults." Then, change the "Character Set" from "Use Unicode Character Set" to "Use Multi-Byte Character Set"

This will fix this problem. There is probably a better solution, but I am not aware of one right now.
